[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm i -g pnpm && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "npx serve dist -s -l tcp://0.0.0.0:${PORT:-3000}"
